### PR TITLE
Added WordPress server and Webmention protocol

### PR DESCRIPTION
**Pull request by pfefferle**

### CODE REVIEW

**Comment by jaywink** [comment]
Thanks! Added as https://github.com/jaywink/nodeinfo2/commit/27838e20b54e5678fabbf9e6dc8ab750b7b949d5 and https://github.com/jaywink/nodeinfo2/commit/9857beb2a7be252c74a89fad9ee2aa73ad1ccbc2 since the repository is mainly hosted in Feneas GitLab and only mirrored here.

One question about the plugin. If someone adds another plugin that adds actual federation using some protocol, does the plugin pick that up automatically or does it have settings for that?

**Comment by pfefferle** [comment]
It can be extended by plugins. The Webmention https://github.com/pfefferle/wordpress-webmention/releases/tag/3.8.8 and OStatus https://github.com/pfefferle/wordpress-ostatus/releases/tag/2.5.4 plugin already extend it.

See https://notiz.blog/.well-known/x-nodeinfo2

**Comment by pfefferle** [comment]
I will add an FAQ to the plugin readme

**Comment by jaywink** [comment]
Epic, thanks for the info, and the plugin! Will promote it in a bit.

**Comment by pfefferle** [comment]
Cool, thanks :)

**Pull request closed without merging**
